package com.example.viewmodel

import androidx.lifecycle.viewModelScope
import com.example.data.MaonatyHouseholdTask
import com.example.data.MaonatyInventoryItem
import com.example.data.MaonatyShoppingItem
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject

fun WomanCompanionViewModel.addInventoryItem(
    name: String,
    category: String,
    quantity: Double,
    minQuantity: Double,
    unit: String,
    priceEstimate: Double,
    id: Int = 0
) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.insertInventoryItem(
            MaonatyInventoryItem(
                id = id,
                name = name,
                category = category,
                quantity = quantity,
                minQuantity = minQuantity,
                unit = unit,
                priceEstimate = priceEstimate
            )
        )
    }
}

fun WomanCompanionViewModel.deleteInventoryItem(item: MaonatyInventoryItem) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.deleteInventoryItem(item)
    }
}

fun WomanCompanionViewModel.clearInventory() {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.clearInventory()
    }
}

fun WomanCompanionViewModel.addShoppingItem(
    name: String,
    category: String,
    quantity: Double,
    unit: String,
    price: Double,
    autoGenerated: Boolean = false
) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.insertShoppingItem(
            MaonatyShoppingItem(
                name = name,
                category = category,
                quantity = quantity,
                unit = unit,
                price = price,
                autoGenerated = autoGenerated
            )
        )
    }
}

fun WomanCompanionViewModel.deleteShoppingItem(item: MaonatyShoppingItem) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.deleteShoppingItem(item)
    }
}

fun WomanCompanionViewModel.toggleShoppingItemBought(item: MaonatyShoppingItem) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.updateShoppingItemStatus(item.id, !item.isBought)
    }
}

fun WomanCompanionViewModel.clearShoppingList() {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.clearShoppingList()
    }
}

fun WomanCompanionViewModel.addHouseholdTask(title: String, category: String, priority: String, dueDate: Long) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.insertHouseholdTask(
            MaonatyHouseholdTask(
                title = title,
                category = category,
                priority = priority,
                dueDate = dueDate
            )
        )
    }
}

fun WomanCompanionViewModel.deleteHouseholdTask(task: MaonatyHouseholdTask) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.deleteHouseholdTask(task)
    }
}

fun WomanCompanionViewModel.toggleTaskCompleted(task: MaonatyHouseholdTask) {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.updateTaskStatus(task.id, !task.isCompleted)
    }
}

fun WomanCompanionViewModel.clearHouseholdTasks() {
    viewModelScope.launch(coroutineExceptionHandler) {
        repository.clearHouseholdTasks()
    }
}

fun WomanCompanionViewModel.generateAutoShoppingList() {
    viewModelScope.launch(coroutineExceptionHandler) {
        val inventory = allInventoryItemsState.value
        val currentShopping = allShoppingItemsState.value
        
        inventory.forEach { invItem ->
            if (invItem.quantity <= invItem.minQuantity) {
                val alreadyAdded = currentShopping.any { shopItem ->
                    shopItem.name.trim().equals(invItem.name.trim(), ignoreCase = true) && !shopItem.isBought
                }
                if (!alreadyAdded) {
                    val buyQty = ((invItem.minQuantity * 2.0) - invItem.quantity).coerceAtLeast(1.0)
                    repository.insertShoppingItem(
                        MaonatyShoppingItem(
                            name = invItem.name,
                            category = invItem.category,
                            quantity = buyQty,
                            unit = invItem.unit,
                            price = invItem.priceEstimate,
                            isBought = false,
                            autoGenerated = true
                        )
                    )
                }
            }
        }
    }
}

fun WomanCompanionViewModel.populateMaonatySampleData() {
    viewModelScope.launch(coroutineExceptionHandler) {
        if (allInventoryItemsState.value.isEmpty()) {
            val samples = listOf(
                MaonatyInventoryItem(name = "أرز مصري فاخر", category = "معلبات وحبوب", quantity = 0.5, minQuantity = 2.0, unit = "كيلوجرام", priceEstimate = 35.0),
                MaonatyInventoryItem(name = "مكرونة قلم", category = "معلبات وحبوب", quantity = 1.0, minQuantity = 3.0, unit = "كيس", priceEstimate = 15.0),
                MaonatyInventoryItem(name = "زيت عباد الشمس", category = "معلبات وحبوب", quantity = 0.4, minQuantity = 1.0, unit = "لتر", priceEstimate = 80.0),
                MaonatyInventoryItem(name = "حليب كامل الدسم", category = "منتجات ألبان", quantity = 3.0, minQuantity = 1.0, unit = "لتر", priceEstimate = 40.0),
                MaonatyInventoryItem(name = "جبنة بيضاء فيتا", category = "منتجات ألبان", quantity = 0.25, minQuantity = 0.5, unit = "كيلوجرام", priceEstimate = 60.0),
                MaonatyInventoryItem(name = "طماطم طازجة", category = "خضار وفواكه", quantity = 0.5, minQuantity = 1.5, unit = "كيلوجرام", priceEstimate = 15.0),
                MaonatyInventoryItem(name = "ليمون أصفر", category = "خضار وفواكه", quantity = 1.0, minQuantity = 0.5, unit = "كيلوجرام", priceEstimate = 25.0),
                MaonatyInventoryItem(name = "صدور فراخ بانيه", category = "لحوم ودواجن", quantity = 0.0, minQuantity = 1.0, unit = "كيلوجرام", priceEstimate = 220.0),
                MaonatyInventoryItem(name = "بهارات لحمة مشكلة", category = "بهارات وتوابل", quantity = 50.0, minQuantity = 100.0, unit = "جرام", priceEstimate = 0.5),
                MaonatyInventoryItem(name = "مسحوق غسيل ملابس", category = "أدوات تنظيف", quantity = 2.5, minQuantity = 1.0, unit = "كيلوجرام", priceEstimate = 180.0),
                MaonatyInventoryItem(name = "ملح طعام ناعم", category = "بهارات وتوابل", quantity = 3.0, minQuantity = 1.0, unit = "كيس", priceEstimate = 5.0)
            )
            samples.forEach { repository.insertInventoryItem(it) }
        }

        if (allHouseholdTasksState.value.isEmpty()) {
            val baseTime = System.currentTimeMillis()
            val tasks = listOf(
                MaonatyHouseholdTask(title = "🧼 تنظيف الثلاجة وترتيب أرفف المطبخ", category = "🧼 تنظيف وترتيب", priority = "⚡ متوسط", dueDate = baseTime + 24 * 60 * 60 * 1000),
                MaonatyHouseholdTask(title = "🛠️ تغيير فلتر مياه المطبخ السبع مراحل", category = "🛠️ صيانة وأعطال", priority = "🔴 عاجل", dueDate = baseTime + 2 * 24 * 60 * 60 * 1000),
                MaonatyHouseholdTask(title = "📦 جرد الخزانة وجهاز التكييف قبل الصيف", category = "📦 جرد وتخزين", priority = "🟢 عادي", dueDate = baseTime + 5 * 24 * 60 * 60 * 1000),
                MaonatyHouseholdTask(title = "📅 سداد فاتورة الكهرباء والغاز الطبيعي", category = "📅 شؤون منزلية", priority = "🔴 عاجل", dueDate = baseTime + 12 * 60 * 60 * 1000)
            )
            tasks.forEach { repository.insertHouseholdTask(it) }
        }
    }
}

fun WomanCompanionViewModel.exportMaonatyBackup(): String {
    markBackupExported()
    return try {
        val root = JSONObject()
        val invArray = JSONArray()
        allInventoryItemsState.value.forEach {
            val obj = JSONObject()
            obj.put("name", it.name)
            obj.put("category", it.category)
            obj.put("quantity", it.quantity)
            obj.put("minQuantity", it.minQuantity)
            obj.put("unit", it.unit)
            obj.put("priceEstimate", it.priceEstimate)
            invArray.put(obj)
        }
        root.put("inventory", invArray)

        val shopArray = JSONArray()
        allShoppingItemsState.value.forEach {
            val obj = JSONObject()
            obj.put("name", it.name)
            obj.put("category", it.category)
            obj.put("quantity", it.quantity)
            obj.put("unit", it.unit)
            obj.put("price", it.price)
            obj.put("isBought", it.isBought)
            obj.put("autoGenerated", it.autoGenerated)
            shopArray.put(obj)
        }
        root.put("shopping", shopArray)

        val taskArray = JSONArray()
        allHouseholdTasksState.value.forEach {
            val obj = JSONObject()
            obj.put("title", it.title)
            obj.put("category", it.category)
            obj.put("priority", it.priority)
            obj.put("dueDate", it.dueDate)
            obj.put("isCompleted", it.isCompleted)
            taskArray.put(obj)
        }
        root.put("tasks", taskArray)

        root.toString(2)
    } catch (e: Exception) {
        ""
    }
}

fun WomanCompanionViewModel.importMaonatyBackup(jsonString: String): Boolean {
    return try {
        val root = JSONObject(jsonString)
        viewModelScope.launch(coroutineExceptionHandler) {
            if (root.has("inventory")) {
                repository.clearInventory()
                val arr = root.getJSONArray("inventory")
                for (i in 0 until arr.length()) {
                    val obj = arr.getJSONObject(i)
                    repository.insertInventoryItem(
                        MaonatyInventoryItem(
                            name = obj.getString("name"),
                            category = obj.getString("category"),
                            quantity = obj.getDouble("quantity"),
                            minQuantity = obj.getDouble("minQuantity"),
                            unit = obj.getString("unit"),
                            priceEstimate = obj.optDouble("priceEstimate", 0.0)
                        )
                    )
                }
            }

            if (root.has("shopping")) {
                repository.clearShoppingList()
                val arr = root.getJSONArray("shopping")
                for (i in 0 until arr.length()) {
                    val obj = arr.getJSONObject(i)
                    repository.insertShoppingItem(
                        MaonatyShoppingItem(
                            name = obj.getString("name"),
                            category = obj.getString("category"),
                            quantity = obj.getDouble("quantity"),
                            unit = obj.getString("unit"),
                            price = obj.optDouble("price", 0.0),
                            isBought = obj.optBoolean("isBought", false),
                            autoGenerated = obj.optBoolean("autoGenerated", false)
                        )
                    )
                }
            }

            if (root.has("tasks")) {
                repository.clearHouseholdTasks()
                val arr = root.getJSONArray("tasks")
                for (i in 0 until arr.length()) {
                    val obj = arr.getJSONObject(i)
                    repository.insertHouseholdTask(
                        MaonatyHouseholdTask(
                            title = obj.getString("title"),
                            category = obj.getString("category"),
                            priority = obj.getString("priority"),
                            dueDate = obj.getLong("dueDate"),
                            isCompleted = obj.optBoolean("isCompleted", false)
                        )
                    )
                }
            }
        }
        true
    } catch (e: Exception) {
        false
    }
}
