package com.example

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.example.data.*
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.IOException

/**
 * Integration and Unit tests for:
 * 1. Maonaty Inventory Management (Stock adjustments, alerts, minQuantity thresholds)
 * 2. Smart Shopping List & Auto-Generation
 * 3. Household Tasks Lifecycle (Priority, completion status)
 * 4. Contraceptive Methods Lifecycle & Tracking
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [36])
class MaonatyAndHouseholdIntegrationTest {

    private lateinit var db: AppDatabase
    private lateinit var dao: WomanCompanionDao

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = db.womanCompanionDao()
    }

    @After
    @Throws(IOException::class)
    fun closeDb() {
        db.close()
    }

    @Test
    fun testInventoryFlow_InsertAdjustAndLowStockDetection() = runBlocking {
        // 1. Insert Inventory Item
        val item = MaonatyInventoryItem(
            id = 0,
            name = "زيت زيتون بكر",
            category = "زيوت وبقوليات",
            quantity = 2.0,
            minQuantity = 1.0,
            unit = "لتر",
            priceEstimate = 120.0
        )
        dao.insertInventoryItem(item)

        // 2. Fetch and verify
        val allItems = dao.getAllInventoryItemsFlow().first()
        assertEquals(1, allItems.size)
        assertEquals("زيت زيتون بكر", allItems[0].name)
        assertEquals(2.0, allItems[0].quantity, 0.001)

        // 3. Update quantity to below minimum threshold
        val updatedItem = allItems[0].copy(quantity = 0.5)
        dao.insertInventoryItem(updatedItem)

        val updatedItems = dao.getAllInventoryItemsFlow().first()
        assertEquals(1, updatedItems.size)
        assertEquals(0.5, updatedItems[0].quantity, 0.001)
        assertTrue("Item should now be recognized as low stock", updatedItems[0].quantity <= updatedItems[0].minQuantity)
    }

    @Test
    fun testShoppingListFlow_AddToggleBoughtAndAutoGeneration() = runBlocking {
        // 1. Insert shopping item
        val shopItem = MaonatyShoppingItem(
            id = 0,
            name = "حليب طبيعي كامل الدسم",
            category = "ألبان",
            quantity = 3.0,
            unit = "لتر",
            price = 45.0,
            isBought = false,
            autoGenerated = false
        )
        dao.insertShoppingItem(shopItem)

        // 2. Toggle bought state
        val inserted = dao.getAllShoppingItemsFlow().first().first()
        dao.insertShoppingItem(inserted.copy(isBought = true))

        val boughtList = dao.getAllShoppingItemsFlow().first()
        assertTrue("Item must be marked as bought", boughtList[0].isBought)

        // 3. Delete single item
        dao.deleteShoppingItem(boughtList[0])
        val emptyList = dao.getAllShoppingItemsFlow().first()
        assertTrue("Shopping list should be empty after deletion", emptyList.isEmpty())
    }

    @Test
    fun testHouseholdTaskFlow_AddToggleAndClear() = runBlocking {
        // 1. Insert high priority task
        val task = MaonatyHouseholdTask(
            id = 0,
            title = "تعقيم زجاجات الرضاعة والماء",
            category = "تعقيم ورعاية",
            priority = "HIGH",
            dueDate = System.currentTimeMillis() + 86400000L,
            isCompleted = false
        )
        dao.insertHouseholdTask(task)

        // 2. Fetch and complete
        val tasks = dao.getAllHouseholdTasksFlow().first()
        assertEquals(1, tasks.size)
        assertEquals("HIGH", tasks[0].priority)

        dao.insertHouseholdTask(tasks[0].copy(isCompleted = true))
        val completedTasks = dao.getAllHouseholdTasksFlow().first()
        assertTrue("Task should be completed", completedTasks[0].isCompleted)

        // 3. Clear all tasks
        dao.clearHouseholdTasks()
        val cleared = dao.getAllHouseholdTasksFlow().first()
        assertTrue("All tasks should be cleared", cleared.isEmpty())
    }

    @Test
    fun testContraceptiveFlow_LogIntakeAndAdherence() = runBlocking {
        val now = System.currentTimeMillis()
        val method = ContraceptiveMethod(
            id = 0,
            type = "PILL",
            startDate = now,
            notes = "تم البدء في موعدها المعتاد 9:00 صباحاً"
        )
        val methodId = dao.insertContraceptiveMethod(method).toInt()
        assertTrue("Contraceptive method ID must be valid", methodId > 0)

        val retrievedMethods = dao.getAllContraceptiveMethodsFlow().first()
        assertEquals(1, retrievedMethods.size)
        assertEquals("PILL", retrievedMethods[0].type)
        assertNull(retrievedMethods[0].endDate)
    }
}
