      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # 🟢 أضف هذا السطر لإعادة إنشاء الملف التالف تلقائياً
      - name: Regenerate Corrupted Gradle Wrapper
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
